### ISSUE TITLE
bioterms landing page

### ISSUE THREAD

**Issue by nsheff** [databio/bioterms#1]
Currently `bioterms.org` points to: 

```
Test Page
This page is used to test the proper operation of the Apache HTTP server after it has been installed. If you can read this page, it means that the Apache HTTP server installed at this site is working properly.
```

We need to think of a landing page.

**Comment by nmagee** [comment]
@nsheff based on closing #3 do you need me to work on more bioterms.org content or do you have that from here? I'm moving on extending my Python in episb.org now but can come back to this as you need.

**Comment by nmagee** [comment]
I did notice one fix we might need @oddodaoddo -- do we need bioterms.org to serve up schemas with or without the `jsonld` suffix?

So these would be equivalent:
http://bioterms.org/schemas/Annotation.jsonld
http://bioterms.org/schemas/Annotation

I only notice because within the actual JSONLD they make mention of schemas without the suffix:

```
  "@graph": Array[19][
    {
      "@id": "http://bioterms.org/schemas/Segment",
      "@type": "rdfs:Class",
      "rdfs:comment": "Basic definition of a dna segment",
      "rdfs:label": "Segment",
      "rdfs:SubclassOf": Array[2][
        {
          "@id": "https://schema.org/Intangible"
        },
        {
          "@id": "https://schema.org/ListItem"
        }
      ]
    }
```

**Comment by nsheff** [comment]
>@nsheff based on closing #3 do you need me to work on more bioterms.org content or do you have that from here? I'm moving on extending my Python in episb.org now but can come back to this as you need. 

I can work on the landing page now. Thanks!

> do we need bioterms.org to serve up schemas with or without the jsonld suffix?

This is related to #5

**Comment by nsheff** [comment]
Latest commit has a more approachable description on the landing page, so I'm closing this issue.
